#!/usr/bin/env bash
# L5 — i4h-workflows project layer (reusable across workflows)

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../scripts/common.sh
source "${SCRIPT_DIR}/../scripts/common.sh"
load_config

info "L5 i4h project setup"

ensure_dirs
download_rti_license || warn "RTI license not ready — set RTI_LICENSE_FILE or RTI_LICENSE_URL"

# If we're already inside the repo, use it
if [[ -f "${DEPLOY_ROOT}/../i4h" && -d "${DEPLOY_ROOT}/../workflows" ]]; then
    I4H_INSTALL_DIR="$(cd "${DEPLOY_ROOT}/.." && pwd)"
    info "Using current repository: ${I4H_INSTALL_DIR}"
else
    clone_or_update_repo
fi

export RTI_LICENSE_FILE
if [[ -f "${RTI_LICENSE_FILE}" ]]; then
    # Symlink for docker manual run path ~/docker/rti/rti_license.dat
    ln -sf "${RTI_LICENSE_FILE}" "${I4H_DOCKER_ROOT}/rti/rti_license.dat" 2>/dev/null || true
fi

# Persist env for interactive shells
ENV_FILE="${HOME}/.i4h-deploy.env"
cat > "${ENV_FILE}" <<EOF
# Generated by i4h deploy L5 — source before running workflows
export I4H_INSTALL_DIR="${I4H_INSTALL_DIR}"
export RTI_LICENSE_FILE="${RTI_LICENSE_FILE}"
export I4H_DOCKER_ROOT="${I4H_DOCKER_ROOT}"
export I4H_CACHE_ROOT="${I4H_CACHE_ROOT}"
EOF
info "Wrote ${ENV_FILE}"

chmod +x "${I4H_INSTALL_DIR}/i4h" 2>/dev/null || true

info "L5 complete — repo at ${I4H_INSTALL_DIR}"
